-- MySQL Script generated by MySQL Workbench
-- Qua 22 Ago 2018 02:32:52 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lpwi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lpwi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lpwi` DEFAULT CHARACTER SET utf8 ;
USE `lpwi` ;

-- -----------------------------------------------------
-- Table `lpwi`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lpwi`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `telefone` INT NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpwi`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lpwi`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `fornecedor` VARCHAR(45) NULL,
  `valorCusto` INT NULL,
  `valorVenda` INT NULL,
  `estoqueAtual` INT NULL,
  `imagem` TEXT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpwi`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lpwi`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NULL,
  `valorFinal` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idvenda`, `cliente_idcliente`),
  INDEX `fk_venda_cliente_idx` (`cliente_idcliente` ASC),
  CONSTRAINT `fk_venda_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `lpwi`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lpwi`.`vendaProdutos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lpwi`.`vendaProdutos` (
  `venda_idvenda` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `qantidade` INT NULL,
  PRIMARY KEY (`venda_idvenda`, `produto_idproduto`),
  INDEX `fk_venda_has_produto_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_venda_has_produto_venda1_idx` (`venda_idvenda` ASC, `idvendaProduto` ASC),
  CONSTRAINT `fk_venda_has_produto_venda1`
    FOREIGN KEY (`venda_idvenda` , `idvendaProduto`)
    REFERENCES `lpwi`.`venda` (`idvenda` , `cliente_idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `lpwi`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
